### ISSUE TITLE
Remove current projectiles/items when changing weapon

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#79]
When I use the Star-shield weapon, and fire that shield at an enemy (or just shoot it), and then I change my weapon or tool - and the Star-shield is still on the screen: I cannot use the newly selected weapon, I have to wait for the Star-Shield weapon to disappear than I can use my newly selected weapon.

Same goes when using Coil Frog, and when I still have the Coil Frog tool (or Time-Freeze tool), and the Frog is still showing - when I try to create another Frog, our hero shoots a basic gun shot (same when using Time-Freeze tool).  So while we are using Coil Frog, Time-Freeze or other tools, we should not be able to shoot normal gunshots - or make it explicit, that while the Frog is down, or time is frozen, we *can* always shoot either the basic gun or something else..

But when changing weapons, we should be able to shoot *immediately* the newly selected weapon or tool (use the tool).  So we should be able to make combos when quickly switching weapons and sometimes "accumulating" the firepower, by adding to existing weapon effects.

**Comment by ghost** [comment]
impairs gameplay very much..

**Comment by protoman** [comment]
OK, by parts.
1. In Megaman games, when you change weapons, any current projectiles are removed so you can start using the new weapon immediately. I tried to make something different. But yeah, I can do remove all current projectiles/effects once changing weapons.

2. You NEED to be able to fire regular shots with timer stopper; otherwise how will you kill the frozen enemies such as Mage Bot? Same for Jet/Coil. Imagine you need to jump to a high place were there is an enemy place to kill him. Do you want each time to change back to normal weapon or other while in the middle of the jump?
