### ISSUE TITLE
[ Rockbot 1 | 1.20.042 | Android | Play Store ] Dark Mine: secret area blocks are badly synced, no way to get back..

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#84]
![bad block sync](https://user-images.githubusercontent.com/33324878/32690313-0b8df36e-c6f5-11e7-8e46-af662d48a26d.gif)

**Comment by protoman** [comment]
Yeah, that is very serious. I've added to the top of my TODO list.
The cause is that I'm resetting object timers when I pause the game, for example in screen transitioning, but during pause, actually objects continue to execute (so we can show them while the screen moves left/right or top/down).
What I can do it not execute objects, only show them, on those transitions, so the timers won't get updated with the time that will be ignored after unpause.

**Comment by protoman** [comment]
OK, while I did fixed the sync issue, this stage was not actually made for you to return from the patch you came, so I've changed the block types to the one that disappear once you step on it. Even on megaman, the disappearing blocks is a one-way path.
If you find other parts that make impossible to return, please let me know.
